=== immersive-web/webxr-input-profiles/packages/registry/dist/schemas/profile.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://immersive-web/webxr-input-profiles/registry/profile.schema.json",
    "type": "object",
    "description": "The root object for an XRInputSource profile.",
    "additionalProperties": true,
    "required": [ "profileId", "fallbackProfileIds", "layouts"],
    "properties": {
        "profileId" : { "$ref": "common.schema.json#/definitions/profileId" },
        "fallbackProfileIds" : {
            "type": "array",
            "items": { "$ref": "common.schema.json#/definitions/profileId" },
            "uniqueItems": true
        },
        "deprecatedProfileIds" : {
            "type": "array",
            "items": { "$ref": "common.schema.json#/definitions/profileId" },
            "uniqueItems": true
        },
        "layouts" : {
            "type": "object",
            "additionalProperties": false,
            "minProperties": 1,
            "properties": {
                "none": { "$ref": "layout.schema.json" },
                "left": { "$ref": "layout.schema.json" },
                "right": { "$ref": "layout.schema.json" },
                "left-right": { "$ref": "layout.schema.json" },
                "left-right-none": { "$ref": "layout.schema.json" }
            },
            "dependencies": {
                "left-right-none": { "not": { "required": ["none", "left", "right", "left-right"] } },
                "left-right": { "not": { "required": ["left", "right", "left-right-none"] } },
                "left": { "required": ["right"], "not": { "required": ["left-right", "left-right-none"] } },
                "right": { "required": ["left"], "not": { "required": ["left-right", "left-right-none"] } },
                "none": { "not": { "required": ["left-right-none"] } }
            }
        }
    }
}

=== immersive-web/webxr-input-profiles/packages/registry/profiles/microsoft/microsoft-mixed-reality.json
{
    "profileId": "microsoft-mixed-reality",
    "fallbackProfileIds": [ "generic-trigger-squeeze-touchpad-thumbstick"],
    "deprecatedProfileIds": [ "windows-mixed-reality" ],
    "layouts" : {
        "left-right" : {
            "selectComponentId": "xr-standard-trigger",
            "components": {
                "xr-standard-trigger": { "type": "trigger" },
                "xr-standard-squeeze": { "type": "squeeze" },
                "xr-standard-touchpad": { "type": "touchpad" },
                "xr-standard-thumbstick": { "type": "thumbstick" },
                "menu" : { "type": "button", "reserved": true }
            },
            "gamepad" : {
                "mapping": "xr-standard",
                "buttons": [
                    "xr-standard-trigger",
                    "xr-standard-squeeze",
                    "xr-standard-touchpad",
                    "xr-standard-thumbstick"
                ],
                "axes":[
                    { "componentId": "xr-standard-touchpad", "axis": "x-axis"},
                    { "componentId": "xr-standard-touchpad", "axis": "y-axis"},
                    { "componentId": "xr-standard-thumbstick", "axis": "x-axis"},
                    { "componentId": "xr-standard-thumbstick", "axis": "y-axis"}
                ]
            }
        }
    }
}
